"""Horner Cscape Model Context Protocol (MCP) package."""
from .server import FastMCP, create_mcp_server, server
from .tools import (
    # 12 Core Tools
    cscape_launch_ide,
    cscape_new_iec_project,
    cscape_open_project,
    cscape_insert_st,
    cscape_insert_st_pou,
    cscape_compile,
    cscape_get_build_output,
    cscape_read_variables,
    cscape_write_variables,
    cscape_import_variables,
    cscape_export_variables,
    cscape_run_simulation,
    # 8 Convenience Wrappers
    cscape_create_project,
    cscape_add_st_pou,
    cscape_validate_st,
    cscape_inspect_variables,
    cscape_compile_project,
    cscape_get_diagnostics,
    cscape_simulate_pou,
    cscape_export_project,
    # 3 Simulation & Register Tools
    cscape_simulate_cycle,
    cscape_read_register,
    cscape_write_register,
    # 5 Phase P3 HMI Tools
    cscape_hmi_inventory,
    cscape_hmi_apply_group,
    cscape_hmi_read_properties,
    cscape_hmi_verify_bindings,
    cscape_hmi_save_close_reopen,
    # 6 Phase P4 Fixture Evolution Tools
    cscape_fixture_request_to_spec,
    cscape_fixture_create,
    cscape_fixture_selective_edit,
    cscape_fixture_revision_impact,
    cscape_fixture_durability_check,
    cscape_fixture_detect_conflict,
    # 5 Phase P5 Modbus PV Provider Tools
    cscape_modbus_create_config,
    cscape_modbus_persist_config,
    cscape_modbus_read_config,
    cscape_modbus_protocol_check,
    cscape_modbus_conversion_doc,
    # Phase P9 Air-Gapped Offline Packaging
    cscape_package_offline_bundle,
    # Scan List Offline Evidence Validation, Inspection & Reconciliation
    cscape_validate_scan_list_evidence,
    cscape_inspect_scan_list,
    cscape_get_scan_list,
    cscape_reconcile_scan_list,
    register_tools,
)
from .resources import register_resources
from .prompts import register_prompts
from . import schemas
from .schemas import (
    # Tool Schemas
    CscapeValidateScanListEvidenceInput,
    CscapeValidateScanListEvidenceOutput,
    CscapeInspectScanListInput,
    CscapeInspectScanListOutput,
    CscapeReconcileScanListInput,
    CscapeReconcileScanListOutput,
    CscapeLaunchIDEInput,
    CscapeLaunchIDEOutput,
    CscapeNewIECProjectInput,
    CscapeNewIECProjectOutput,
    CscapeOpenProjectInput,
    CscapeOpenProjectOutput,
    CscapePackageOfflineBundleInput,
    CscapePackageOfflineBundleOutput,
    CscapeInsertSTInput,
    CscapeInsertSTOutput,
    CscapeCompileInput,
    CscapeCompileOutput,
    CscapeGetBuildOutputInput,
    CscapeGetBuildOutputOutput,
    CscapeImportVariablesInput,
    CscapeImportVariablesOutput,
    CscapeExportVariablesInput,
    CscapeExportVariablesOutput,
    CscapeRunSimulationInput,
    CscapeRunSimulationOutput,
    # Aliases
    LaunchIDEInput,
    LaunchIDEOutput,
    NewIECProjectInput,
    NewIECProjectOutput,
    OpenProjectInput,
    OpenProjectOutput,
    InsertSTInput,
    InsertSTOutput,
    CompileInput,
    CompileOutput,
    GetBuildOutputInput,
    GetBuildOutputOutput,
    ImportVariablesInput,
    ImportVariablesOutput,
    ExportVariablesInput,
    ExportVariablesOutput,
    RunSimulationInput,
    RunSimulationOutput,
    # Registry
    TOOL_SCHEMAS,
    get_tool_input_schema,
    get_tool_output_schema,
    list_tool_schemas,
    validate_tool_input,
    validate_tool_output,
)

__all__ = [
    "FastMCP",
    "create_mcp_server",
    "server",
    # 12 Core Tools
    "cscape_launch_ide",
    "cscape_new_iec_project",
    "cscape_open_project",
    "cscape_insert_st",
    "cscape_insert_st_pou",
    "cscape_compile",
    "cscape_get_build_output",
    "cscape_read_variables",
    "cscape_write_variables",
    "cscape_import_variables",
    "cscape_export_variables",
    "cscape_run_simulation",
    # 8 Convenience Wrappers
    "cscape_create_project",
    "cscape_add_st_pou",
    "cscape_validate_st",
    "cscape_inspect_variables",
    "cscape_compile_project",
    "cscape_get_diagnostics",
    "cscape_simulate_pou",
    "cscape_export_project",
    # 3 Simulation & Register Tools
    "cscape_simulate_cycle",
    "cscape_read_register",
    "cscape_write_register",
    # 5 Phase P3 HMI Tools
    "cscape_hmi_inventory",
    "cscape_hmi_apply_group",
    "cscape_hmi_read_properties",
    "cscape_hmi_verify_bindings",
    "cscape_hmi_save_close_reopen",
    # 6 Phase P4 Fixture Evolution Tools
    "cscape_fixture_request_to_spec",
    "cscape_fixture_create",
    "cscape_fixture_selective_edit",
    "cscape_fixture_revision_impact",
    "cscape_fixture_durability_check",
    "cscape_fixture_detect_conflict",
    # 5 Phase P5 Modbus PV Provider Tools
    "cscape_modbus_create_config",
    "cscape_modbus_persist_config",
    "cscape_modbus_read_config",
    "cscape_modbus_protocol_check",
    "cscape_modbus_conversion_doc",
    # Air-Gapped Offline Packaging
    "cscape_package_offline_bundle",
    # Scan List Offline Evidence Validation, Inspection & Reconciliation
    "cscape_validate_scan_list_evidence",
    "cscape_inspect_scan_list",
    "cscape_get_scan_list",
    "cscape_reconcile_scan_list",
    "CscapeValidateScanListEvidenceInput",
    "CscapeValidateScanListEvidenceOutput",
    "CscapeInspectScanListInput",
    "CscapeInspectScanListOutput",
    "CscapeReconcileScanListInput",
    "CscapeReconcileScanListOutput",
    # Server Registration & Meta
    "register_tools",
    "register_resources",
    "register_prompts",
    "schemas",
    "CscapePackageOfflineBundleInput",
    "CscapePackageOfflineBundleOutput",
    "CscapeLaunchIDEInput",
    "CscapeLaunchIDEOutput",
    "CscapeNewIECProjectInput",
    "CscapeNewIECProjectOutput",
    "CscapeOpenProjectInput",
    "CscapeOpenProjectOutput",
    "CscapeInsertSTInput",
    "CscapeInsertSTOutput",
    "CscapeCompileInput",
    "CscapeCompileOutput",
    "CscapeGetBuildOutputInput",
    "CscapeGetBuildOutputOutput",
    "CscapeImportVariablesInput",
    "CscapeImportVariablesOutput",
    "CscapeExportVariablesInput",
    "CscapeExportVariablesOutput",
    "CscapeRunSimulationInput",
    "CscapeRunSimulationOutput",
    "LaunchIDEInput",
    "LaunchIDEOutput",
    "NewIECProjectInput",
    "NewIECProjectOutput",
    "OpenProjectInput",
    "OpenProjectOutput",
    "InsertSTInput",
    "InsertSTOutput",
    "CompileInput",
    "CompileOutput",
    "GetBuildOutputInput",
    "GetBuildOutputOutput",
    "ImportVariablesInput",
    "ImportVariablesOutput",
    "ExportVariablesInput",
    "ExportVariablesOutput",
    "RunSimulationInput",
    "RunSimulationOutput",
    "TOOL_SCHEMAS",
    "get_tool_input_schema",
    "get_tool_output_schema",
    "list_tool_schemas",
    "validate_tool_input",
    "validate_tool_output",
]

