"""
Cscape / Straton K5 IEC 61131-3 Project Manager.
Handles project creation, directory layout, ST POU injection, and persistence.
"""
import os
import json
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import List, Optional, Dict, Any, Union
Union_Path_Str = Union[str, Path]
from datetime import datetime

@dataclass
class POUInfo:
    name: str
    pou_type: str  # PROGRAM, FUNCTION_BLOCK, FUNCTION
    file_path: str
    created_at: str
    st_code: str
    variable_count: int = 0
    statement_count: int = 0

class CscapeProject:
    """
    Manages a Cscape Straton K5 project directory structure.
    Strictly focuses on IEC 61131-3 Structured Text POUs (No Advanced Ladder).
    """
    def __init__(self, project_dir: Union_Path_Str, name: str = "", controller: str = "XL4"):
        self.project_dir = Path(project_dir).resolve()
        self.name = name or self.project_dir.name
        self.controller = controller
        self.manifest_file = self.project_dir / "cscape_project.json"
        self.pous_dir = self.project_dir / "pous"
        self.pous: Dict[str, POUInfo] = {}

    @classmethod
    def create(cls, project_dir: Union_Path_Str, name: str, controller: str = "XL4") -> "CscapeProject":
        """Initializes a new Cscape / Straton K5 project directory structure."""
        p_dir = Path(project_dir).resolve()
        p_dir.mkdir(parents=True, exist_ok=True)
        
        pous_dir = p_dir / "pous"
        pous_dir.mkdir(exist_ok=True)

        default_dir = p_dir / "Default"
        default_dir.mkdir(exist_ok=True)

        # 1. appli.k5p - Straton project definition
        k5p_path = p_dir / "appli.k5p"
        if not k5p_path.exists():
            k5p_content = (
                ";K5 project - Generated by Horner Cscape MCP Toolchain\n"
                ";Structured Text Native Engine\n\n"
                "/A,<5>65537,65538,131073,131074,131075,131076,131077,131078,131080,\n"
                "</A,end>\n"
                "/G,GLOBAL\n"
                "/G,RETAIN\n"
                "</G,end>\n"
            )
            k5p_path.write_text(k5p_content, encoding="utf-8")

        # 2. appli.CPO - Compiler options
        cpo_path = p_dir / "appli.CPO"
        if not cpo_path.exists():
            cpo_content = (
                "[Options]\n"
                "Target=K5_SIM\n"
                "Optimization=Speed\n"
                "WarningAsError=0\n"
                "Language=ST\n"
            )
            cpo_path.write_text(cpo_content, encoding="utf-8")

        # 3. appli.lge - Localization
        lge_path = p_dir / "appli.lge"
        if not lge_path.exists():
            lge_path.write_text("0,English\n", encoding="utf-8")

        # 4. K5DBXS.INI
        ini_path = p_dir / "K5DBXS.INI"
        if not ini_path.exists():
            ini_content = "[K5DB]\nVersion=10.2\nFormat=XML\n"
            ini_path.write_text(ini_content, encoding="utf-8")

        # 5. Default/appli.txt
        txt_path = default_dir / "appli.txt"
        if not txt_path.exists():
            txt_content = f"[long]\nA-<PROJECT>={name}\n"
            txt_path.write_text(txt_content, encoding="utf-8")

        # 6. cscape_project.json - Manifest
        project = cls(p_dir, name=name, controller=controller)
        project._save_manifest()
        return project

    @classmethod
    def load(cls, project_dir: Union_Path_Str) -> "CscapeProject":
        """Loads an existing Cscape project from directory."""
        p_dir = Path(project_dir).resolve()
        manifest_file = p_dir / "cscape_project.json"
        if not manifest_file.exists():
            raise FileNotFoundError(f"Project manifest not found at {manifest_file}")

        data = json.loads(manifest_file.read_text(encoding="utf-8"))
        proj = cls(p_dir, name=data.get("name", p_dir.name), controller=data.get("controller", "XL4"))

        # Load POUs
        for pou_dict in data.get("pous", []):
            pou_file = Path(pou_dict["file_path"])
            st_code = ""
            if pou_file.exists():
                st_code = pou_file.read_text(encoding="utf-8")
            pou_info = POUInfo(
                name=pou_dict["name"],
                pou_type=pou_dict["pou_type"],
                file_path=str(pou_file),
                created_at=pou_dict.get("created_at", ""),
                st_code=st_code,
                variable_count=pou_dict.get("variable_count", 0),
                statement_count=pou_dict.get("statement_count", 0),
            )
            proj.pous[pou_info.name] = pou_info

        return proj

    def inject_pou(self, name: str, st_code: str, pou_type: str = "PROGRAM") -> POUInfo:
        """
        Injects an IEC 61131-3 Structured Text POU into the project.
        Saves the .st file, updates project tables, and refreshes the manifest.
        """
        clean_name = name.strip()
        if not clean_name:
            raise ValueError("POU name cannot be empty")

        pou_type_upper = pou_type.upper()
        if pou_type_upper not in ("PROGRAM", "FUNCTION_BLOCK", "FUNCTION"):
            raise ValueError(f"Invalid POU type: {pou_type}")

        # Write POU file
        pou_file = self.pous_dir / f"{clean_name}.st"
        pou_file.write_text(st_code, encoding="utf-8")

        # Analyze basic metrics from code
        from src.parser.parser import Parser
        var_count = 0
        stmt_count = 0
        try:
            p = Parser.from_source(st_code)
            ast = p.parse()
            for vb in ast.var_blocks:
                var_count += len(vb.declarations)
            stmt_count = len(ast.body)
        except Exception:
            pass

        pou_info = POUInfo(
            name=clean_name,
            pou_type=pou_type_upper,
            file_path=str(pou_file),
            created_at=datetime.now().isoformat(),
            st_code=st_code,
            variable_count=var_count,
            statement_count=stmt_count
        )

        self.pous[clean_name] = pou_info
        self._update_appli_k5p(clean_name, pou_type_upper)
        self._save_manifest()
        return pou_info

    def get_pou(self, name: str) -> Optional[POUInfo]:
        """Retrieves POU by name (case-insensitive)."""
        for k, v in self.pous.items():
            if k.upper() == name.upper():
                return v
        return None

    def list_pous(self) -> List[POUInfo]:
        """Lists all registered POUs in project."""
        return list(self.pous.values())

    def _update_appli_k5p(self, pou_name: str, pou_type: str) -> None:
        """Appends POU entry to appli.k5p."""
        k5p_path = self.project_dir / "appli.k5p"
        if not k5p_path.exists():
            return
        content = k5p_path.read_text(encoding="utf-8")
        entry = f"/P,{pou_name},{pou_type},ST\n"
        if entry not in content:
            # Insert before </P,end> or append
            if "</P,end>" in content:
                content = content.replace("</P,end>", f"{entry}</P,end>")
            else:
                content += f"\n{entry}</P,end>\n"
            k5p_path.write_text(content, encoding="utf-8")

    def _save_manifest(self) -> None:
        """Serializes project manifest to JSON."""
        data = {
            "name": self.name,
            "controller": self.controller,
            "iec_engine": "Straton K5 Structured Text",
            "updated_at": datetime.now().isoformat(),
            "pous": [asdict(p) for p in self.pous.values()]
        }
        self.manifest_file.write_text(json.dumps(data, indent=2), encoding="utf-8")

